import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import MobileHeader from "@/components/Layout/MobileHeader";
import MobileBottomNav from "@/components/Layout/MobileBottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[]`}
      >
        <div className=" ">
          <Header />
        </div>
        {/* <div className="lg:hidden ">
          <MobileHeader />
        </div> */}
        <div className="bg-[#F6F6F6]">
        {children}
        </div>
        <div className="hidden lg:block">
          <Footer />
        </div>
        <div className="lg:hidden pt-20">
          <MobileBottomNav />
        </div>


      </body>
    </html>
  );
}
